// ── GreenVerify AI Demo / Fallback Data ──
import type {
  StatCards,
  Verification,
  VerificationScoreDistribution,
  CreditStandardDistribution,
  CreditNFT,
  MarketplaceListing,
  MarketplaceStats,
} from './types';

export const demoStats: StatCards = {
  totalCreditsVerified: 2_458_730,
  projectsVerified: 387,
  activeListings: 124,
  avgScore: 82.4,
};

export const demoVerifications: Verification[] = [
  {
    id: 'v-001',
    projectName: 'Amazon Reforestation Initiative',
    projectType: 'Reforestation',
    country: 'Brazil',
    score: 94,
    riskLevel: 'Low',
    status: 'Verified',
    date: '2025-01-15',
  },
  {
    id: 'v-002',
    projectName: 'Saharan Solar Farm Alpha',
    projectType: 'Renewable Energy',
    country: 'Morocco',
    score: 88,
    riskLevel: 'Low',
    status: 'Verified',
    date: '2025-01-12',
  },
  {
    id: 'v-003',
    projectName: 'Methane Capture – Dairy Consortium',
    projectType: 'Methane Capture',
    country: 'New Zealand',
    score: 71,
    riskLevel: 'Medium',
    status: 'Verified',
    date: '2025-01-10',
  },
  {
    id: 'v-004',
    projectName: 'Baltic Wind Corridor',
    projectType: 'Renewable Energy',
    country: 'Estonia',
    score: 56,
    riskLevel: 'High',
    status: 'Pending',
    date: '2025-01-08',
  },
  {
    id: 'v-005',
    projectName: 'Steel Plant CCS Retrofit',
    projectType: 'Industrial',
    country: 'South Korea',
    score: 43,
    riskLevel: 'High',
    status: 'Failed',
    date: '2025-01-05',
  },
];

export const demoScoreDistribution: VerificationScoreDistribution[] = [
  { range: '0-20', count: 12 },
  { range: '21-40', count: 28 },
  { range: '41-60', count: 65 },
  { range: '61-80', count: 142 },
  { range: '81-100', count: 140 },
];

export const demoStandardDistribution: CreditStandardDistribution[] = [
  { name: 'VCS', value: 178, color: '#10b981' },
  { name: 'Gold Standard', value: 132, color: '#f59e0b' },
  { name: 'CDM', value: 77, color: '#6366f1' },
];

export const demoCreditNFTs: CreditNFT[] = [
  {
    tokenId: 'GV-1001',
    projectName: 'Amazon Reforestation Initiative',
    creditAmount: 50000,
    vintageYear: 2024,
    creditStandard: 'Gold Standard',
    country: 'Brazil',
    ownerAddress: '0x7a3b...f82e',
    mintedDate: '2024-11-20',
    txHash: '0xab12...9f3d',
    projectType: 'Reforestation',
  },
  {
    tokenId: 'GV-1002',
    projectName: 'Saharan Solar Farm Alpha',
    creditAmount: 120000,
    vintageYear: 2024,
    creditStandard: 'VCS',
    country: 'Morocco',
    ownerAddress: '0x9c4e...a1b7',
    mintedDate: '2024-12-01',
    txHash: '0xcd34...e5f6',
    projectType: 'Renewable Energy',
  },
  {
    tokenId: 'GV-1003',
    projectName: 'Methane Capture – Dairy Consortium',
    creditAmount: 18000,
    vintageYear: 2023,
    creditStandard: 'VCS',
    country: 'New Zealand',
    ownerAddress: '0x2d8f...c4a9',
    mintedDate: '2024-10-15',
    txHash: '0xef56...1a2b',
    projectType: 'Methane Capture',
  },
  {
    tokenId: 'GV-1004',
    projectName: 'Baltic Wind Corridor',
    creditAmount: 85000,
    vintageYear: 2024,
    creditStandard: 'Gold Standard',
    country: 'Estonia',
    ownerAddress: '0x5e1a...7d3f',
    mintedDate: '2024-12-10',
    txHash: '0xgh78...3c4d',
    projectType: 'Renewable Energy',
  },
  {
    tokenId: 'GV-1005',
    projectName: 'Indonesian Mangrove Restoration',
    creditAmount: 32000,
    vintageYear: 2023,
    creditStandard: 'CDM',
    country: 'Indonesia',
    ownerAddress: '0x8b2c...e6f1',
    mintedDate: '2024-09-28',
    txHash: '0xij90...5e6f',
    projectType: 'Reforestation',
  },
  {
    tokenId: 'GV-1006',
    projectName: 'Kenya Geothermal Phase II',
    creditAmount: 200000,
    vintageYear: 2025,
    creditStandard: 'VCS',
    country: 'Kenya',
    ownerAddress: '0x3f7d...b9a2',
    mintedDate: '2025-01-05',
    txHash: '0xkl12...7g8h',
    projectType: 'Renewable Energy',
  },
  {
    tokenId: 'GV-1007',
    projectName: 'Steel Plant CCS Retrofit',
    creditAmount: 45000,
    vintageYear: 2024,
    creditStandard: 'CDM',
    country: 'South Korea',
    ownerAddress: '0x6a4e...d2c8',
    mintedDate: '2024-11-30',
    txHash: '0xmn34...9i0j',
    projectType: 'Industrial',
  },
  {
    tokenId: 'GV-1008',
    projectName: 'Patagonia Wind Array',
    creditAmount: 67000,
    vintageYear: 2024,
    creditStandard: 'Gold Standard',
    country: 'Argentina',
    ownerAddress: '0x1c9f...f4e7',
    mintedDate: '2024-12-18',
    txHash: '0xop56...1k2l',
    projectType: 'Renewable Energy',
  },
];

export const demoListings: MarketplaceListing[] = [
  {
    tokenId: 'GV-1001',
    projectName: 'Amazon Reforestation Initiative',
    creditAmount: 50000,
    pricePOT: 12500,
    sellerAddress: '0x7a3b...f82e',
    listedDate: '2025-01-15',
    creditStandard: 'Gold Standard',
    projectType: 'Reforestation',
    vintageYear: 2024,
  },
  {
    tokenId: 'GV-1002',
    projectName: 'Saharan Solar Farm Alpha',
    creditAmount: 120000,
    pricePOT: 28800,
    sellerAddress: '0x9c4e...a1b7',
    listedDate: '2025-01-14',
    creditStandard: 'VCS',
    projectType: 'Renewable Energy',
    vintageYear: 2024,
  },
  {
    tokenId: 'GV-1003',
    projectName: 'Methane Capture – Dairy Consortium',
    creditAmount: 18000,
    pricePOT: 3960,
    sellerAddress: '0x2d8f...c4a9',
    listedDate: '2025-01-13',
    creditStandard: 'VCS',
    projectType: 'Methane Capture',
    vintageYear: 2023,
  },
  {
    tokenId: 'GV-1004',
    projectName: 'Baltic Wind Corridor',
    creditAmount: 85000,
    pricePOT: 18700,
    sellerAddress: '0x5e1a...7d3f',
    listedDate: '2025-01-12',
    creditStandard: 'Gold Standard',
    projectType: 'Renewable Energy',
    vintageYear: 2024,
  },
  {
    tokenId: 'GV-1005',
    projectName: 'Indonesian Mangrove Restoration',
    creditAmount: 32000,
    pricePOT: 7680,
    sellerAddress: '0x8b2c...e6f1',
    listedDate: '2025-01-11',
    creditStandard: 'CDM',
    projectType: 'Reforestation',
    vintageYear: 2023,
  },
  {
    tokenId: 'GV-1006',
    projectName: 'Kenya Geothermal Phase II',
    creditAmount: 200000,
    pricePOT: 42000,
    sellerAddress: '0x3f7d...b9a2',
    listedDate: '2025-01-10',
    creditStandard: 'VCS',
    projectType: 'Renewable Energy',
    vintageYear: 2025,
  },
];

export const demoMarketplaceStats: MarketplaceStats = {
  totalVolumeTraded: 1_850_400,
  numberOfTrades: 2_341,
  floorPrice: 0.18,
  avgPrice: 0.24,
};

// ── Country flag emoji mapping ──
export const countryFlags: Record<string, string> = {
  Brazil: '🇧🇷',
  Morocco: '🇲🇦',
  'New Zealand': '🇳🇿',
  Estonia: '🇪🇪',
  'South Korea': '🇰🇷',
  Indonesia: '🇮🇩',
  Kenya: '🇰🇪',
  Argentina: '🇦🇷',
  India: '🇮🇳',
  China: '🇨🇳',
  USA: '🇺🇸',
  Germany: '🇩🇪',
  Australia: '🇦🇺',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Colombia: '🇨🇴',
  Thailand: '🇹🇭',
  Vietnam: '🇻🇳',
  Philippines: '🇵🇭',
  Nigeria: '🇳🇬',
  'South Africa': '🇿🇦',
  Chile: '🇨🇱',
  Peru: '🇵🇪',
  'Papua New Guinea': '🇵🇬',
  Cambodia: '🇰🇭',
  Myanmar: '🇲🇲',
  Tanzania: '🇹🇿',
  Uganda: '🇺🇬',
  Ghana: '🇬🇭',
  Mozambique: '🇲🇿',
};

export function getCountryFlag(country: string): string {
  return countryFlags[country] ?? '🌍';
}
